I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 67, in script
    with Fade(0.5)
TypeError: Fade() takes at least 3 arguments (3 given)

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 67, in script
    with Fade(0.5)
  File "/Users/rayvenenoso/Desktop/OJT - rocalworks/visual novel/renpy-6.18.3-sdk/renpy/ast.py", line 1229, in execute
    renpy.exports.with_statement(trans, paired)
  File "/Users/rayvenenoso/Desktop/OJT - rocalworks/visual novel/renpy-6.18.3-sdk/renpy/exports.py", line 1229, in with_statement
    return renpy.game.interface.do_with(trans, paired, clear=clear)
  File "/Users/rayvenenoso/Desktop/OJT - rocalworks/visual novel/renpy-6.18.3-sdk/renpy/display/core.py", line 1810, in do_with
    clear=clear)
  File "/Users/rayvenenoso/Desktop/OJT - rocalworks/visual novel/renpy-6.18.3-sdk/renpy/display/core.py", line 2149, in interact
    repeat, rv = self.interact_core(preloads=preloads, **kwargs)
  File "/Users/rayvenenoso/Desktop/OJT - rocalworks/visual novel/renpy-6.18.3-sdk/renpy/display/core.py", line 2356, in interact_core
    new_widget=layers_root)
  File "/Users/rayvenenoso/Desktop/OJT - rocalworks/visual novel/renpy-6.18.3-sdk/renpy/curry.py", line 38, in __call__
    **dict(self.kwargs.items() + kwargs.items()))
TypeError: Fade() takes at least 3 arguments (3 given)

Darwin-13.0.0-x86_64-i386-64bit
Ren'Py 6.18.3.761
Eijiro's Storybook 0.0
